version: "3.9"

volumes:
  db-data:

services:
  app:
    container_name: ${CONTAINER_PREFIX}-app
    build:
      context: ../.
      dockerfile: docker/app/Dockerfile
      args:
        - APP_DIR=${APP_DIR}
        - UID=${UID}
        - GID=${GID}
        - INSTALL_GECKO_AND_FIREFOX=${INSTALL_GECKO_AND_FIREFOX}
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
    env_file:
      - ./.env
    volumes:
      - ../.:${APP_DIR}
      - ../${APP_FOLDER}/${STATIC_FILES_FOLDER}:${APP_DIR}/${APP_FOLDER}/${STATIC_FILES_FOLDER}
      - ../${APP_FOLDER}/${MEDIA_FILES_FOLDER}:${APP_DIR}/${APP_FOLDER}/${MEDIA_FILES_FOLDER}
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - db
    networks:
      - app_network
      - db_network
    tty: true
    stdin_open: true
    entrypoint: ./docker/app/entrypoint.sh

  webserver:
    container_name: ${CONTAINER_PREFIX}-webserver
    build:
      context: ./nginx
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - UPSTREAM_CONTAINER=${CONTAINER_PREFIX}-app
    volumes:
      - ./nginx/:${APP_DIR}/${APP_FOLDER}/nginx
      - ../${APP_FOLDER}/${STATIC_FILES_FOLDER}:${APP_DIR}/${APP_FOLDER}/${STATIC_FILES_FOLDER}
      - ../${APP_FOLDER}/${MEDIA_FILES_FOLDER}:${APP_DIR}/${APP_FOLDER}/${MEDIA_FILES_FOLDER}
    ports:
      - ${APPLICATION_PORT}:80
    depends_on:
      - app
    networks:
      - app_network
    entrypoint: ${APP_DIR}/${APP_FOLDER}/nginx/entrypoint.sh
    command:
      - nginx
      - -g
      - daemon off;

  db:
    container_name: ${CONTAINER_PREFIX}-db
    image: postgres:14.4-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_DB_PORT}:5432
    networks:
      - db_network

networks:
  app_network:
  db_network:
