version: "3.9"

volumes:
  db-data:

services:
  app:
    container_name: ${CONTAINER_PREFIX}-app
    build:
      context: ../.
      dockerfile: docker/app/Dockerfile
      args:
        - APP_DIR=${APP_DIR}
        - UID=${UID}
        - GID=${GID}
        - INSTALL_GECKO_AND_FIREFOX=${INSTALL_GECKO_AND_FIREFOX}
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ../.:${APP_DIR}
      - ../${APP_FOLDER}/${STATIC_FILES_FOLDER}:${APP_DIR}/${APP_FOLDER}/${STATIC_FILES_FOLDER}
      - ../${APP_FOLDER}/${MEDIA_FILES_FOLDER}:${APP_DIR}/${APP_FOLDER}/${MEDIA_FILES_FOLDER}
    depends_on:
      - db
    networks:
      - app_network
      - db_network
    tty: true
    stdin_open: true
    entrypoint: ./docker/app/entrypoint.sh

  webserver:
    container_name: ${CONTAINER_PREFIX}-webserver
    build:
      context: ./nginx
      args:
        - APPLICATION_ADDRESS=${APPLICATION_ADDRESS}
        - UPSTREAM_CONTAINER=${CONTAINER_PREFIX}-app
        - APP_DIR=${APP_DIR}
        - APP_FOLDER=${APP_FOLDER}
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ../${APP_FOLDER}/${STATIC_FILES_FOLDER}:${APP_DIR}/${APP_FOLDER}/${STATIC_FILES_FOLDER}
      - ../${APP_FOLDER}/${MEDIA_FILES_FOLDER}:${APP_DIR}/${APP_FOLDER}/${MEDIA_FILES_FOLDER}
    ports:
      - ${APPLICATION_PORT}:80
    depends_on:
      - app
    networks:
      - app_network

  db:
    container_name: ${CONTAINER_PREFIX}-db
    image: postgres:14.4-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - db_network

networks:
  app_network:
  db_network:
